### ISSUE TITLE
Time in mp_tournament is not visible

### ISSUE THREAD

**Issue by jas1992fasola** [Hypnootize/Flame-Hud#1]
![20190717170021_1](https://user-images.githubusercontent.com/42492735/61386560-cab5c300-a8b4-11e9-9127-5b488a8158fe.jpg)

after capping points while mp_tournament is set to 1 the text with time is not visible (you can see tiny part of it under round timer)

**Comment by Hypnootize** [comment]
I forgot about this :( took about a year but is fixed now!
